[workspace]
resolver = "2"
members = ["stm32f411-fsr", "abi", "emulator", "dancepad-cli"]

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"
