[package]
name = "dancepad-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
abi = { version = "0.1.0", path = "../abi", features = ["host"] }
console = "0.15.8"
env_logger = "0.11.5"
indicatif = "0.17.9"
log = "0.4.22"
parking_lot = "0.12.3"
serial2 = "0.2.28"
