[package]
name = "dancepad-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
abi = { version = "0.1.0", path = "../abi", features = ["host"] }
eframe = "0.29.1"
egui_extras = "0.29.1"
env_logger = "0.11.5"
log = "0.4.22"
parking_lot = "0.12.3"
serial2 = "0.2.28"
